// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqgufypvdjqqpwvtyxoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZ3VmeXB2ZGpxcXB3dnR5eG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODE0MTcsImV4cCI6MjA3MDU1NzQxN30.fmnCcZ3ZCwk0k4k92GlfH1fqkiwB773A-TY1UeL3zaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});